// 백엔드 정책 API가 구현되기 전까지 사용하는 mock 데이터.
// VITE_USE_MOCK_DATA=false 로 설정하면 실제 API를 호출한다.
// 백엔드가 준비되면 이 파일은 삭제 또는 테스트용으로만 유지.

import type { Policy, PolicyDetail } from '../types';

export const MOCK_POLICIES: Policy[] = [
  {
    id: '1',
    title: '2025 청년 월세 지원사업',
    org: '서울주택도시공사(SH)',
    category: 'Housing',
    categoryKr: '주거',
    deadline: 'D-3',
    support: '최대 240만원',
    desc: '서울시 거주 무주택 청년들을 위한 최대 20만원 월세 지원 프로젝트입니다.',
    region: '서울',
    bookmarked: true,
  },
  {
    id: '2',
    title: '청년 일자리 도약 장려금',
    org: '고용노동부',
    category: 'Jobs',
    categoryKr: '일자리',
    deadline: 'D-7',
    support: '최대 1,200만원',
    desc: '취업 애로 청년을 정규직으로 채용하는 중소기업에 인건비를 지원합니다.',
    region: '전국',
    bookmarked: true,
  },
  {
    id: '3',
    title: '청년 마음건강 바우처',
    org: '보건복지부',
    category: 'Welfare',
    categoryKr: '복지',
    deadline: 'D-12',
    support: '최대 50만원',
    desc: '심리적 어려움을 겪는 청년에게 전문 심리상담 서비스를 지원합니다.',
    region: '전국',
    bookmarked: false,
  },
  {
    id: '4',
    title: '역세권 청년주택 (SH)',
    org: '서울주택도시공사(SH)',
    category: 'Housing',
    categoryKr: '주거',
    deadline: '상시',
    support: '주거 지원',
    desc: '역세권의 양질의 주택을 청년, 신혼부부에게 시세보다 저렴하게 공급합니다.',
    region: '서울',
    bookmarked: true,
  },
  {
    id: '5',
    title: '청년일자리 도약장려금',
    org: '고용노동부',
    category: 'Jobs',
    categoryKr: '일자리',
    deadline: 'D-30',
    support: '최대 1,200만원',
    desc: '취업애로청년을 채용한 중소기업에 인건비를 지원하여 청년의 취업을 돕습니다.',
    region: '전국',
    bookmarked: false,
  },
  {
    id: '6',
    title: '청년 내일채움공제',
    org: '중소벤처기업부',
    category: 'Jobs',
    categoryKr: '일자리',
    deadline: 'D-45',
    support: '최대 1,200만원',
    desc: '중소기업에 취업한 청년이 2년간 근속하면 목돈을 마련할 수 있는 사업입니다.',
    region: '전국',
    bookmarked: false,
  },
  {
    id: '7',
    title: '국민취업지원제도',
    org: '고용노동부',
    category: 'Jobs',
    categoryKr: '일자리',
    deadline: '상시',
    support: '최대 300만원',
    desc: '취업을 원하는 청년에게 취업지원 서비스를 제공하고 생계지원도 함께 합니다.',
    region: '전국',
    bookmarked: false,
  },
  {
    id: '8',
    title: '청년 내일저축계좌',
    org: '보건복지부',
    category: 'Welfare',
    categoryKr: '복지',
    deadline: 'D-60',
    support: '최대 1,440만원',
    desc: '일하는 저소득 청년이 매월 저축하면 정부가 지원금을 추가 적립해줍니다.',
    region: '전국',
    bookmarked: false,
  },
];

export const MOCK_POLICY_DETAILS: Record<string, PolicyDetail> = {
  '1': {
    policyId: '1',
    title: '2025 청년 월세 지원사업',
    category: '주거',
    deadlineText: 'D-3',
    organization: '서울주택도시공사(SH)',
    supportScale: '최대 240만원',
    description: '이 사업은 서울시에 거주하는 무주택 청년들을 위해 최대 월 20만원, 최대 12개월간 월세를 지원하는 사업입니다. 부모님과 별도 거주하는 청년을 대상으로 주거 안정을 위한 핵심 지원 정책입니다.',
    benefits: ['월세 최대 20만원 지원', '최대 12개월간 지원', '총 최대 240만원 지급'],
    detailUrl: 'https://youth.seoul.go.kr/site/youth/rent',
    applicationStartDate: '2025-02-27',
    applicationEndDate: '2025-12-31',
    eligibility: [
      { label: '연령', value: '19세 ~ 39세' },
      { label: '지역', value: '서울특별시' },
      { label: '소득', value: '제한 없음 또는 확인 필요' },
      { label: '취업 상태', value: '제한 없음 또는 확인 필요' },
      { label: '자산', value: '제한 없음 또는 확인 필요' },
      { label: '학력', value: '제한 없음 또는 확인 필요' },
      { label: '장애 여부', value: '제한 없음 또는 확인 필요' },
      { label: '성별', value: '제한 없음 또는 확인 필요' },
    ],
  },
  '2': {
    policyId: '2',
    title: '청년 일자리 도약 장려금',
    category: '일자리',
    deadlineText: 'D-7',
    organization: '고용노동부',
    supportScale: '최대 1,200만원',
    description: '이 사업은 구직에 어려움을 느끼는 청년들을 위해 심층 상담과 맞춤형 역량 강화 프로그램을 제공하며, 수료 시 총 300만원의 지원금을 지급하는 고용노동부 핵심 정책입니다.',
    benefits: ['인건비 월 최대 80만원 지원', '최대 12개월 지원', '추가 장려금 100만원'],
    detailUrl: 'https://www.work24.go.kr',
    applicationStartDate: '2025-06-01',
    applicationEndDate: '2025-06-30',
    eligibility: [
      { label: '연령', value: '18세 ~ 34세' },
      { label: '지역', value: '전국' },
      { label: '소득', value: '제한 없음' },
      { label: '취업 상태', value: '미취업자' },
      { label: '자산', value: '제한 없음 또는 확인 필요' },
      { label: '학력', value: '제한 없음 또는 확인 필요' },
      { label: '장애 여부', value: '제한 없음 또는 확인 필요' },
      { label: '성별', value: '제한 없음 또는 확인 필요' },
    ],
  },
  '3': {
    policyId: '3',
    title: '청년 마음건강 바우처',
    category: '복지',
    deadlineText: 'D-12',
    organization: '보건복지부',
    supportScale: '최대 50만원',
    description: '심리적 어려움을 겪고 있는 청년들에게 전문 심리상담 기관을 연결하고 바우처 형태로 상담 비용을 지원합니다.',
    benefits: ['심리상담 회당 최대 5만원 지원', '연 10회 지원', '전문 상담사 연결'],
    detailUrl: 'https://www.bokjiro.go.kr',
    applicationStartDate: '2025-07-01',
    applicationEndDate: '2025-07-19',
    eligibility: [
      { label: '연령', value: '19세 ~ 34세' },
      { label: '지역', value: '전국' },
      { label: '소득', value: '중위 120% 이하' },
      { label: '취업 상태', value: '제한 없음 또는 확인 필요' },
      { label: '자산', value: '제한 없음 또는 확인 필요' },
      { label: '학력', value: '제한 없음 또는 확인 필요' },
      { label: '장애 여부', value: '제한 없음 또는 확인 필요' },
      { label: '성별', value: '제한 없음 또는 확인 필요' },
    ],
  },
  '4': {
    policyId: '4',
    title: '역세권 청년주택 (SH)',
    category: '주거',
    deadlineText: '상시',
    organization: '서울주택도시공사(SH)',
    supportScale: '주거 지원',
    description: '지하철역 350m 이내 역세권에 위치한 양질의 청년주택을 시세의 85% 이하로 공급하는 사업입니다.',
    benefits: ['시세 85% 이하 임대료', '역세권 위치 주택', '최대 6년 거주 가능'],
    detailUrl: 'https://www.i-sh.co.kr',
    applicationStartDate: null,
    applicationEndDate: null,
    eligibility: [
      { label: '연령', value: '19세 ~ 39세' },
      { label: '지역', value: '서울특별시' },
      { label: '소득', value: '제한 없음 또는 확인 필요' },
      { label: '취업 상태', value: '제한 없음 또는 확인 필요' },
      { label: '자산', value: '제한 없음 또는 확인 필요' },
      { label: '학력', value: '제한 없음 또는 확인 필요' },
      { label: '장애 여부', value: '제한 없음 또는 확인 필요' },
      { label: '성별', value: '제한 없음 또는 확인 필요' },
    ],
  },
  '5': {
    policyId: '5',
    title: '청년일자리 도약장려금',
    category: '일자리',
    deadlineText: 'D-30',
    organization: '고용노동부',
    supportScale: '최대 1,200만원',
    description: '중소기업에 취업한 청년이 2년간 매월 12.5만원을 납입하면, 기업과 정부가 추가로 납입하여 만기 시 1,200만원을 수령할 수 있는 공제 사업입니다.',
    benefits: ['청년 납입 300만원', '기업 지원 400만원', '정부 지원 500만원 = 총 1,200만원'],
    detailUrl: 'https://www.sbcplan.or.kr',
    applicationStartDate: '2025-09-02',
    applicationEndDate: '2025-09-30',
    eligibility: [
      { label: '연령', value: '15세 ~ 34세' },
      { label: '지역', value: '전국' },
      { label: '소득', value: '제한 없음 또는 확인 필요' },
      { label: '취업 상태', value: '중소기업 재직자' },
      { label: '자산', value: '제한 없음 또는 확인 필요' },
      { label: '학력', value: '제한 없음 또는 확인 필요' },
      { label: '장애 여부', value: '제한 없음 또는 확인 필요' },
      { label: '성별', value: '제한 없음 또는 확인 필요' },
    ],
  },
  '6': {
    policyId: '6',
    title: '청년 내일채움공제',
    category: '일자리',
    deadlineText: 'D-45',
    organization: '중소벤처기업부',
    supportScale: '최대 1,200만원',
    description: '중소기업에 취업한 청년이 2년간 매월 12.5만원을 납입하면, 기업과 정부가 추가로 납입하여 만기 시 1,200만원을 수령할 수 있는 공제 사업입니다.',
    benefits: ['청년 납입 300만원', '기업 지원 400만원', '정부 지원 500만원 = 총 1,200만원'],
    detailUrl: 'https://www.sbcplan.or.kr',
    applicationStartDate: '2025-09-02',
    applicationEndDate: '2025-09-30',
    eligibility: [
      { label: '연령', value: '15세 ~ 34세' },
      { label: '지역', value: '전국' },
      { label: '소득', value: '제한 없음 또는 확인 필요' },
      { label: '취업 상태', value: '중소기업 재직자' },
      { label: '자산', value: '제한 없음 또는 확인 필요' },
      { label: '학력', value: '제한 없음 또는 확인 필요' },
      { label: '장애 여부', value: '제한 없음 또는 확인 필요' },
      { label: '성별', value: '제한 없음 또는 확인 필요' },
    ],
  },
  '7': {
    policyId: '7',
    title: '국민취업지원제도',
    category: '일자리',
    deadlineText: '상시',
    organization: '고용노동부',
    supportScale: '최대 300만원',
    description: '취업을 희망하는 청년에게 맞춤형 취업지원 서비스와 생계 지원을 동시에 제공하는 고용안전망 사업입니다.',
    benefits: ['구직촉진수당 월 50만원', '최대 6개월 지원', '취업지원 프로그램 연계'],
    detailUrl: 'https://www.work24.go.kr',
    applicationStartDate: null,
    applicationEndDate: null,
    eligibility: [
      { label: '연령', value: '15세 ~ 69세' },
      { label: '지역', value: '전국' },
      { label: '소득', value: '기준 중위 60% 이하' },
      { label: '취업 상태', value: '미취업자' },
      { label: '자산', value: '제한 없음 또는 확인 필요' },
      { label: '학력', value: '제한 없음 또는 확인 필요' },
      { label: '장애 여부', value: '제한 없음 또는 확인 필요' },
      { label: '성별', value: '제한 없음 또는 확인 필요' },
    ],
  },
  '8': {
    policyId: '8',
    title: '청년 내일저축계좌',
    category: '복지',
    deadlineText: 'D-60',
    organization: '보건복지부',
    supportScale: '최대 1,440만원',
    description: '일하는 저소득 청년이 3년간 매월 10만원을 저축하면 정부가 추가 지원금을 적립하여 목돈 마련을 지원합니다.',
    benefits: ['청년 납입 월 10만원', '정부 지원 월 최대 30만원', '3년 후 최대 1,440만원'],
    detailUrl: 'https://www.bokjiro.go.kr',
    applicationStartDate: '2025-11-01',
    applicationEndDate: '2025-11-22',
    eligibility: [
      { label: '연령', value: '19세 ~ 34세' },
      { label: '지역', value: '전국' },
      { label: '소득', value: '기준 중위 100% 이하' },
      { label: '취업 상태', value: '근로자' },
      { label: '자산', value: '기준 충족' },
      { label: '학력', value: '제한 없음 또는 확인 필요' },
      { label: '장애 여부', value: '제한 없음 또는 확인 필요' },
      { label: '성별', value: '제한 없음 또는 확인 필요' },
    ],
  },
};
